version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./server/.env
    network_mode: 'host'
    ports:
      - '3001:3001'
    volumes:
      - ./server:/app
      - /app/node_modules
    command: sh -c "npm run dev"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./client/.env
    networks:
      - stickers
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    command: sh -c "npm run dev -- --host"

networks:
  stickers:
    driver: bridge
